**Unidade curricular:** Visualização de Dados 2026/27 (FCUL)

**Grupo VD12:** Diva Manuel · Lêrice Germano · Matilde Quitério

## 1. Tema e dataset

O dataset escolhdo para este projeto foi o **Health Indicators Dataset for Forecasting (WHO)**, um dataset com mais de 200 países, 60 anos de indicacores de saúde disponibilizado no kaggle.

**Link:** https://www.kaggle.com/datasets/patelris/who-health-dataset-43-indicators-200-countries 

**Fonte:** A fonte primária de referencia é o Banco Mundial (WDI). O kaggle é um intermediário que reune e reorganiza a informação e a fornece em datasets. 

**O conjunto de dados está estruturado em três ficheiros:**
- `health_indicators.csv`: Painel temporal com 48 variáveis, 211 países e territórios, cobrindo o período de 2000 a 2024 (5 275 linhas observações).

- `country_latest.csv` : Tabela com o registo anual mais recente disponível por país e por indicador.
- `indicator_metadata.csv`: Metadados descritivos com o código, unidade e categoria de cada indicador.

## 2. Objetivo Geral
Construir uma aplicação de visual analytics que permita explorar como evoluiu a esperança média de vida desde 2000, em que medida a riqueza e o investimento em saúde a explicam, que países fogem à regra e que perfís de países existem. 

### 2.1. Perguntas analíticas

**1. Evolução da esperança de vida**
- 1) Como evoluiu a esperança média desde 2000? 
- 2) Existem diferenças entre regiões? 
- 3) Existem diferenças entre grupos de rendimento? 
- 4) A disparidade entre países ricos e pobres aumentou ou diminuiu? 

**2. Desenvolvimento económico e saúde**
- 1) O PIB per capita influencia a esperança de vida? 
- 2) O investimento em saúde influencia a esperança de vida? 
- 3) Há países com bons resultados apesar de poucos recursos? 

**3. Comparação entre homens e mulheres**
- 1) Como varia a esperança média de vida masculina e feminina? 

**4. Mortalidade**
- 1) Países com elevada esperança média de vida têm eobrigatoriamente baixa mortalidade? 
- 2) Que tipo de mortalidade continua elevada em países desenvolvidos? 
- 3) Como varia a mortalidade infantil e materna?

**5. Geografia**
- 1) Onde estão os melhores e piores resultados de saúde? 

**6. Clustering**
- 1) Existem perfis de países semelhantes?

### 2.1. Perguntas analíticas SUGESTAO DE REESTRUTURAÇÃO
**Tema 1: Evolução da esperança de vida - Tendencias globais, disparidade e género**
1. **Evolução Temporal e Geográfica:** De que forma a esperança de vida progrediu ao longo do tempo (2000–2024) entre diferentes regiões do globo e grupos de rendimento (income groups)?
2. **Dinâmica do Fosso de Rendimento (Gap Rico vs. Pobre):** Verificou-se uma convergência ou um alargamento da disparidade na esperança média de vida entre os países de rendimento elevado e os países de baixo rendimento?
3. **Disparidades de Género (Gender Gap):** Como varia a esperança de vida masculina face à feminina ao longo do tempo, e essa diferença de longevidade entre sexos é mais acentuada em certas regiões ou patamares de rendimento?


**Tema 2: Desenvolvimento Económico e Eficiência dos Recursos em Saúde**
1. **Riqueza vs. Longevidade:** De que modo o PIB per capita influencia a esperança média de vida e a partir de que patamar se observam retornos decrescentes?
2. **Investimento Setorial em Saúde:** Em que medida o gasto específico em saúde (per capita e % do PIB) se correlaciona com ganhos na esperança de vida para além do mero efeito do PIB?
3. **Casos de Eficiência e Anomalias (Outliers):** Que países conseguem alcançar uma elevada esperança de vida apesar de disporem de baixos recursos económicos, e quais apresentam resultados aquém do esperado face aos elevados gastos?

**Tema 3: Como se distribuem geograficamente os padrões e causas de mortalidade no mundo e que perfis de países emergem dessa realidade através de agrupamento**
1. **Paradoxo da Mortalidade:** DPaíses com elevada esperança de vida têm obrigatoriamente baixa taxa bruta de mortalidade, ou o envelhecimento populacional altera essa relação? 
2. **Geografia da Sobrevivência Infantil e Materna:** Onde se concentram espacialmente os melhores e piores indicadores de mortalidade infantil e materna a nível global?
3. **Perfis de Países (Clustering)** Aplicando técnicas computacionais de agrupamento (clustering) às variáveis de mortalidade e saúde, que perfis naturais de países emergem e até que ponto coincidem com as regiões geográficas habituais?

## 3.  Carregamento de dados

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Carregamento dos ficheiros
df_health_indicators = pd.read_csv("health_indicators.csv")
df_meta = pd.read_csv("indicator_metadata.csv")
df_latest = pd.read_csv("country_latest.csv")


print(f"Shape do dataset de indicadores: {df_health_indicators.shape}")
print(f"Paises analisados: {df_health_indicators['country_name'].nunique()}")

Shape do dataset de indicadores: (5275, 48)
Paises analisados: 211

In [9]:
df_health_indicators.head()

,country_code,country_name,region,income_level,year,population,population_growth,urban_pct,life_expectancy,life_expectancy_male,...,stunting_pct,wasting_pct,overweight_children_pct,undernourishment_pct,fertility_rate,adolescent_fertility,prenatal_care_pct,gdp_per_capita,gdp_per_capita_ppp,poverty_rate
0,ABW,Aruba,Latin America & Caribbean,High income,2000,90588.0,1.030817,65.354550,72.939,70.149,...,NaN,NaN,NaN,NaN,1.845,43.729,NaN,20681.023027,30245.706974,NaN
1,ABW,Aruba,Latin America & Caribbean,High income,2001,91439.0,0.935033,65.335114,73.044,70.251,...,NaN,NaN,NaN,NaN,1.813,40.463,NaN,20740.132583,31920.239073,NaN
2,ABW,Aruba,Latin America & Caribbean,High income,2002,92074.0,0.692052,65.282069,73.135,70.364,...,NaN,NaN,NaN,NaN,1.800,38.185,NaN,21307.248251,31888.508737,NaN
3,ABW,Aruba,Latin America & Caribbean,High income,2003,93128.0,1.138229,65.198292,73.236,70.488,...,NaN,NaN,NaN,NaN,1.808,37.807,NaN,21949.485996,32507.084315,NaN
4,ABW,Aruba,Latin America & Caribbean,High income,2004,95138.0,2.135358,65.088653,73.223,70.487,...,NaN,NaN,NaN,NaN,1.819,38.761,NaN,23700.631990,35059.273098,NaN

### 3.1 Exploração e diagnóstico inicial

#### 3.1.1 Analise de variáveis categóricas

In [19]:
df_health_indicators.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5275 entries, 0 to 5274
Data columns (total 48 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   country_code                   5275 non-null   object
 1   country_name                   5275 non-null   object
 2   region                         5275 non-null   object
 3   income_level                   5275 non-null   object
 4   year                           5275 non-null   int64
 5   population                     5275 non-null   float64
 6   population_growth              5274 non-null   float64
 7   urban_pct                      5275 non-null   float64
 8   life_expectancy                5275 non-null   float64
 9   life_expectancy_male           5275 non-null   float64
 10  life_expectancy_female         5275 non-null   float64
 11  death_rate                     5275 non-null   float64
 12  birth_rate                     5275 non-null   float64
 13  health_expenditure_pct_gdp     4514 non-null   float64
 14  health_expenditure_per_capita  4511 non-null   float64
 15  physicians_per_1000            2831 non-null   float64
 16  hospital_beds_per_1000         2898 non-null   float64
 17  nurses_per_1000                2832 non-null   float64
 18  under5_mortality               4850 non-null   float64
 19  neonatal_mortality             4850 non-null   float64
 20  maternal_mortality             4608 non-null   float64
 21  tb_incidence                   5057 non-null   float64
 22  hiv_incidence                  3614 non-null   float64
 23  communicable_death_pct         1098 non-null   float64
 24  noncommunicable_death_pct      1098 non-null   float64
 25  smoking_male                   1304 non-null   float64
 26  smoking_female                 1304 non-null   float64
 27  obesity_pct                    0 non-null      float64
 28  alcohol_per_capita             3870 non-null   float64
 29  diabetes_pct                   420 non-null    float64
 30  safe_water_pct                 3591 non-null   float64
 31  sanitation_pct                 3469 non-null   float64
 32  handwashing_pct                1781 non-null   float64
 33  immunization_measles           4755 non-null   float64
 34  immunization_dpt               4755 non-null   float64
 35  immunization_bcg               3882 non-null   float64
 36  immunization_pol3              4755 non-null   float64
 37  immunization_hib3              3733 non-null   float64
 38  stunting_pct                   844 non-null    float64
 39  wasting_pct                    843 non-null    float64
 40  overweight_children_pct        806 non-null    float64
 41  undernourishment_pct           3762 non-null   float64
 42  fertility_rate                 5275 non-null   float64
 43  adolescent_fertility           5275 non-null   float64
 44  prenatal_care_pct              741 non-null    float64
 45  gdp_per_capita                 5110 non-null   float64
 46  gdp_per_capita_ppp             4838 non-null   float64
 47  poverty_rate                   1827 non-null   float64
dtypes: float64(43), int64(1), object(4)
memory usage: 1.9+ MB

In [16]:
print("Regiões presentes:")
print(df_health_indicators['region'].unique())

print("\nGrupos de rendimento:")
print(df_health_indicators['income_level'].unique())

Regiões presentes:
['Latin America & Caribbean '
 'Middle East, North Africa, Afghanistan & Pakistan' 'Sub-Saharan Africa '
 'Europe & Central Asia' 'East Asia & Pacific' 'South Asia'
 'North America']

Grupos de rendimento:
['High income' 'Low income' 'Lower middle income' 'Upper middle income'
 'Not classified']

##### Observação sobre as variáveis categóricas
- **`region`**: Existem 7 regiões globais representadas
- **`income_level`**: Os países estão divididos em 4 patamares de riqueza (*Low income*, *Lower middle income*, *Lower middle income*, *High income* and *Not classified*)

- `country_code`, `country_name`,`region`, `income_level` são interpretados como texto genérico *(object)*. É possivel existirem espaços em branco acidentais no inicio ou fim das palavras em texto genérico. Essa existencia de espaços residuias provoca erros silenciosos em operações de filtragem e pesquisa, por isso será necessário fazer um tratamento nesta variáveis para garantir que os nomes fiquem padronizados e pesquisáveis sem inconsistência

- A classificação económica dos países *(income_level)*, por estar como object não tem uma hierarquia definida no dataset. Será necessário tornar esta variável numa variável categórica ordinal para assegurar que todos os gráficos e agregações respeitem essa progressão socioeconómica.

#### 3.1.2 Analise de duplicados

In [4]:
#Verificação de registos duplicados por país/ano
duplicados = df_health_indicators.duplicated(subset=['country_name', 'year']).sum()
print(f"Registos duplicados por país/ano: {duplicados}")

Registos duplicados por país/ano: 0

O resultado de registos duplicados foi 0, o que garante que a combinação (country_name, year) é única, ou seja, não existe nenhum país repetido no mesmo ano.

#### 3.1.2 Analise de missing values

In [6]:
#Diagnóstico de valores nulos (missing values) nas variáveis dos temas das nossas perguntas analíticas

colunas_analise = ['life_expectancy', 'life_expectancy_male','life_expectancy_female','gdp_per_capita', 'health_expenditure_per_capita', 'health_expenditure_pct_gdp', 'death_rate']

#construção da tabela de diagnóstico de valores nulos
tabela_nulos = pd.DataFrame({
    "Total_registos": len(df_health_indicators),
    "Valores_nulos": df_health_indicators[colunas_analise].isnull().sum(),
    "Percentagem_nulos": df_health_indicators[colunas_analise].isnull().mean() * 100}).round(2)

tabela_nulos

,Total_registos,Valores_nulos,Percentagem_nulos
life_expectancy,5275,0,0.00
life_expectancy_male,5275,0,0.00
life_expectancy_female,5275,0,0.00
gdp_per_capita,5275,165,3.13
health_expenditure_per_capita,5275,764,14.48
health_expenditure_pct_gdp,5275,761,14.43
death_rate,5275,0,0.00

Variáveis como life_expectancy,life_expectancy_male,life_expectancy_female, death_rate têm zero valores em falta. Isto significa que as análises que envolvam estas variáveis possam ser feita sem perda de amostra ou sem necessidade de interpolação.

As variáveis económicas e de despesa em saúde ja apresentam uma certa percentagem de missing values, o que pode afetar algum tratamento das questões analíticas: 

- gdp_per_capita apresenta 3.13% de valores em falta (165 observações em falta)
- health_expenditure_per_capita apresenta 14.48% de valores em falta (764 observações em falta)
- health_expenditure_pct_gdp apresenta 14.43% de valores em falta (761 observações em falta)

Para interpretar com rigor metodológico a causa destes nulos, desenvolvemos alguns testes por **ano** e por **pais**

In [ ]:
nulos_anuais = df_health_indicators.groupby('year')[['gdp_per_capita','health_expenditure_per_capita','health_expenditure_pct_gdp']].apply(lambda x: x.isnull().sum())

print("Evolução dos nulos por ano: ")
nulos_anuais

Evolução dos nulos por ano:

,gdp_per_capita,health_expenditure_per_capita,health_expenditure_pct_gdp
year,,,
2000,12,29,29
2001,11,29,29
2002,7,28,28
2003,7,26,26
2004,7,26,26
2005,7,26,26
2006,6,26,26
2007,6,26,26
2008,4,26,26
2009,3,26,26
2010,3,25,25
2011,2,24,24
2012,4,24,24
2013,4,22,22
2014,3,22,22
2015,4,22,22
2016,5,22,22
2017,5,21,21
2018,5,20,20
2019,5,20,20
2020,6,20,20
2021,6,21,20
2022,7,22,21
2023,13,22,21
2024,23,189,189

- De 2000 até 2023, o número de paises sem dados de despesa em saúde manteve-se estável, oscilando entre 20 e 29. Em 2024 esse valor salta abruptamente para 189 países sem dados de despesas de saúde, ou seja 86.6% do dataset não tem dados financeiros em 2024. Isto faz com que qualquer gráfico ou modelo que use deapesas (health_expenditure) deve focar-se na janela 2000 a 2022/2023 para evitar distorções.

- O Pib per capita (`gdp_per_capita`) tem apenas entre só entre 2 a 7 paises em falta por ano, havendo uma ligeira subida em 2023 (13 nulos) e 2024 (23 nulos).

## 4.  Limpeza e Transformação de dados

In [23]:
#criação da cópia do dataset para preservar o original e isolar transformações e limpeza de dados
dados = df_health_indicators.copy()

# Limpeza simples: retirar espaços a mais no texto nas variáveis interpretadas como object

dados['region'] = dados['region'].str.strip()
dados['income_level'] = dados['income_level'].str.strip()
dados['country_name'] = dados['country_name'].str.strip()
dados['country_code'] = dados['country_code'].str.strip()

# Definir a ordem lógica dos grupos de rendimento (do menor para o maior) para efeitos de visualização
ordem_rendimento = ['Low income', 'Lower middle income', 'Upper middle income', 'High income']
dados['income_level'] = pd.Categorical(dados['income_level'], categories=ordem_rendimento, ordered=True)

# 5. Exploração Visual dos Dados

## Tema 1: Evolução da esperança de vida - Tendencias globais, disparidade e género

### 1.Como evoluiu  a esperança média de vida global entre 2000 e 2024?